jenes::performance::DeJongTest
int jenes.performance.DeJongTest.POPULATION_SIZE
Referenced by jenes.performance.DeJongTest.DeJongTest, jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5.
int jenes.performance.DeJongTest.GENERATION_LIMIT
Referenced by jenes.performance.DeJongTest.DeJongTest, jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5.
int jenes.performance.DeJongTest.CHROMOSOME_SIZE
Referenced by jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5.
double jenes.performance.DeJongTest.MIN_VALUE
Referenced by jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5, jenes.performance.DeJongTest.convert.
double jenes.performance.DeJongTest.MAX_VALUE
Referenced by jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5, jenes.performance.DeJongTest.convert.
GeneticAlgorithm<BitwiseChromosome> jenes.performance.DeJongTest.ga
Referenced by jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5.
jenes.performance.DeJongTest.DeJongTest(int problem, int popSize, int genLimit)
References jenes.performance.DeJongTest.POPULATION_SIZE, jenes.performance.DeJongTest.GENERATION_LIMIT, jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5.
Referenced by jenes.performance.DeJongTest.main.
void jenes.performance.DeJongTest.solve()
void jenes.performance.DeJongTest.buildProblem1()
References jenes.performance.DeJongTest.MIN_VALUE, jenes.performance.DeJongTest.MAX_VALUE, jenes.performance.DeJongTest.CHROMOSOME_SIZE, jenes.performance.DeJongTest.POPULATION_SIZE, jenes.performance.DeJongTest.ga, jenes.performance.DeJongTest.GENERATION_LIMIT, jenes.performance.DeJongTest.convert, jenes.chromosome.BitwiseChromosome.getIntValueAt.
Referenced by jenes.performance.DeJongTest.DeJongTest.
void jenes.performance.DeJongTest.buildProblem2()
References jenes.performance.DeJongTest.MIN_VALUE, jenes.performance.DeJongTest.MAX_VALUE, jenes.performance.DeJongTest.CHROMOSOME_SIZE, jenes.performance.DeJongTest.POPULATION_SIZE, jenes.performance.DeJongTest.ga, jenes.performance.DeJongTest.GENERATION_LIMIT, jenes.performance.DeJongTest.convert, jenes.chromosome.BitwiseChromosome.getIntValueAt.
Referenced by jenes.performance.DeJongTest.DeJongTest.
void jenes.performance.DeJongTest.buildProblem3()
References jenes.performance.DeJongTest.MIN_VALUE, jenes.performance.DeJongTest.MAX_VALUE, jenes.performance.DeJongTest.CHROMOSOME_SIZE, jenes.performance.DeJongTest.POPULATION_SIZE, jenes.performance.DeJongTest.ga, jenes.performance.DeJongTest.GENERATION_LIMIT, jenes.performance.DeJongTest.convert, jenes.chromosome.BitwiseChromosome.getIntValueAt.
Referenced by jenes.performance.DeJongTest.DeJongTest.
void jenes.performance.DeJongTest.buildProblem4()
References jenes.performance.DeJongTest.MIN_VALUE, jenes.performance.DeJongTest.MAX_VALUE, jenes.performance.DeJongTest.CHROMOSOME_SIZE, jenes.performance.DeJongTest.POPULATION_SIZE, jenes.performance.DeJongTest.ga, jenes.performance.DeJongTest.GENERATION_LIMIT, jenes.performance.DeJongTest.convert, jenes.chromosome.BitwiseChromosome.getIntValueAt, jenes.utils.Random.getInstance.
Referenced by jenes.performance.DeJongTest.DeJongTest.
void jenes.performance.DeJongTest.buildProblem5()
References jenes.performance.DeJongTest.MIN_VALUE, jenes.performance.DeJongTest.MAX_VALUE, jenes.performance.DeJongTest.CHROMOSOME_SIZE, jenes.performance.DeJongTest.POPULATION_SIZE, jenes.performance.DeJongTest.ga, jenes.performance.DeJongTest.GENERATION_LIMIT, jenes.performance.DeJongTest.convert, jenes.chromosome.BitwiseChromosome.getIntValueAt.
Referenced by jenes.performance.DeJongTest.DeJongTest.
final double jenes.performance.DeJongTest.convert(int x)
References jenes.performance.DeJongTest.MAX_VALUE, jenes.performance.DeJongTest.MIN_VALUE.
Referenced by jenes.performance.DeJongTest.buildProblem1, jenes.performance.DeJongTest.buildProblem2, jenes.performance.DeJongTest.buildProblem3, jenes.performance.DeJongTest.buildProblem4, jenes.performance.DeJongTest.buildProblem5.
static void jenes.performance.DeJongTest.main(String[] args)
References jenes.performance.DeJongTest.DeJongTest.