jenes::utils::AbstractLogger
List<String> jenes.utils.AbstractLogger.schema
The statistics schema
Referenced by jenes.utils.AbstractLogger.put, jenes.utils.AbstractLogger.isRecordComplete, jenes.utils.CSVLogger.CSVLogger, jenes.utils.XLSLogger.XLSLogger.
Map<String, Object> jenes.utils.AbstractLogger.record
The table of value to store. It is the current record to fill.
Referenced by jenes.utils.AbstractLogger.put, jenes.utils.AbstractLogger.isRecordComplete, jenes.utils.CSVLogger.store, jenes.utils.XLSLogger.store.
boolean jenes.utils.AbstractLogger.closed
Referenced by jenes.utils.AbstractLogger.put, jenes.utils.AbstractLogger.log, jenes.utils.AbstractLogger.save, jenes.utils.AbstractLogger.close.
jenes.utils.AbstractLogger.AbstractLogger(String[] schema)
Creates a new logger providing a schema schema - the logging schema
String [] jenes.utils.AbstractLogger.getSchema()
Returns the logging schemathe array of fields
Iterator<String> jenes.utils.AbstractLogger.getFields()
Returns the list of schema fieldsthe iterator of fields
final void jenes.utils.AbstractLogger.put(String key, Object value)
Puts a value into the current record. key - the statistics name value - the statistics value
References jenes.utils.AbstractLogger.closed, jenes.utils.AbstractLogger.schema, jenes.utils.AbstractLogger.record.
final Object jenes.utils.AbstractLogger.get(String key)
Retrieves a statistics from the current record. key - the statistics name the statistics value
boolean jenes.utils.AbstractLogger.isRecordComplete()
Returns true if the record is completetrue if the record is complete
References jenes.utils.AbstractLogger.schema, jenes.utils.AbstractLogger.record.
final void jenes.utils.AbstractLogger.log()
Logs a current record by storing it and making the record empty. This is the method to invoke to store the current recorrd.
References jenes.utils.AbstractLogger.closed, jenes.utils.AbstractLogger.store.
void jenes.utils.AbstractLogger.save()
Saves cached records on media. If the logger is closed this operation is not allowed.
References jenes.utils.AbstractLogger.closed, jenes.utils.AbstractLogger.doSave.
void jenes.utils.AbstractLogger.close()
Saves cached records on media and closes the logger. If the logger is closed this operation is not allowed.
References jenes.utils.AbstractLogger.closed, jenes.utils.AbstractLogger.doSave, jenes.utils.AbstractLogger.doClose.
abstract void jenes.utils.AbstractLogger.store()
Stores the current record.
Referenced by jenes.utils.AbstractLogger.log.
abstract void jenes.utils.AbstractLogger.doSave()
Saves cached records on media
Referenced by jenes.utils.AbstractLogger.save, jenes.utils.AbstractLogger.close.
abstract void jenes.utils.AbstractLogger.doClose()
Closes the logger. Any further log is not allowed.
Referenced by jenes.utils.AbstractLogger.close, jenes.utils.AbstractLogger.finalize.
void jenes.utils.AbstractLogger.finalize()
References jenes.utils.AbstractLogger.doClose.